name: Build and Store Container

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main

jobs:
  build-container:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image to GitHub Container Registry
      uses: docker/build-push-action@v4
      with:
        context: ./Container
        tags: ghcr.io/${{ github.repository_owner }}/deepinfer:latest

    - name: Run container from GitHub Container Registry
      run: docker run ghcr.io/${{ github.repository_owner }}/deepinfer:latest
